// frontend/app/components/landing/Faq.vue
<template>
  <section class="section bg-(--bg-section) py-20">
    <div class="container--narrow">
      <!-- Header -->
      <div
        ref="headerRef"
        class="mx-auto max-w-2xl text-center transition-all duration-700"
        :class="
          headerVisible
            ? 'opacity-100 translate-y-0'
            : 'opacity-0 translate-y-6'
        "
      >
        <Tag value="FAQ" severity="success" class="rounded-full!" />
        <h2
          class="mt-4 font-display text-3xl font-extrabold tracking-tight text-(--text-primary) sm:text-4xl"
        >
          Questions fréquentes
        </h2>
        <p class="mt-3 text-base leading-relaxed text-(--text-secondary)">
          Tout ce que vous devez savoir avant de commencer votre préparation.
        </p>
      </div>

      <!-- Accordion + CTA -->
      <div ref="contentRef" class="mt-12">
        <Transition name="p-collapsible">
          <div v-if="contentVisible" class="grid">
            <div class="overflow-hidden">
              <Accordion class="flex flex-col gap-2.5">
                <AccordionPanel
                  v-for="item in faqs"
                  :key="item.q"
                  :value="item.q"
                >
                  <AccordionHeader
                    class="rounded-2xl! border! border-(--border-color)! bg-(--bg-card)! px-5! py-4.5! text-[0.9375rem] font-semibold! text-(--text-primary)! hover:bg-(--bg-hover)! [&_.p-accordionheader-toggle-icon]:text-primary-600!"
                  >
                    {{ item.q }}
                  </AccordionHeader>
                  <AccordionContent>
                    <p
                      class="m-0! border-t border-(--border-color) bg-(--bg-card)! px-5 py-4 text-[0.9375rem] leading-[1.75] text-(--text-secondary)"
                    >
                      {{ item.a }}
                    </p>
                  </AccordionContent>
                </AccordionPanel>
              </Accordion>

              <!-- CTA contact -->
              <div
                class="mt-10 flex flex-col items-center gap-4 rounded-2xl border border-(--border-color) bg-(--bg-ground) p-8 text-center"
              >
                <p class="text-[0.9375rem] text-(--text-secondary)">
                  Vous ne trouvez pas de réponse à votre question ?
                </p>
                <NuxtLink to="/contact">
                  <Button
                    label="Contactez-nous"
                    icon="pi pi-envelope"
                    outlined
                    class="rounded-xl! border-primary-600! font-semibold! text-primary-600!"
                  />
                </NuxtLink>
              </div>
            </div>
          </div>
        </Transition>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from "vue";

const headerRef = ref(null);
const contentRef = ref(null);
const headerVisible = ref(false);
const contentVisible = ref(false);

let observer;

onMounted(() => {
  observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        if (entry.target === headerRef.value) headerVisible.value = true;
        if (entry.target === contentRef.value) contentVisible.value = true;
        observer.unobserve(entry.target);
      });
    },
    { threshold: 0.15 },
  );

  if (headerRef.value) observer.observe(headerRef.value);
  if (contentRef.value) observer.observe(contentRef.value);
});

onUnmounted(() => observer?.disconnect());

const faqs = [
  {
    q: "Les tests sont-ils similaires à l’examen réel ?",
    a: "Oui, nos tests reproduisent exactement les conditions du TCF Canada officiel : même format, même durée, même niveau de difficulté. Vous serez dans les meilleures conditions le jour J.",
  },
  {
    q: "Combien de temps faut-il pour se préparer au TCF Canada ?",
    a: "Cela dépend de votre niveau de départ et de l’objectif NCLC visé. En général, 3 à 6 semaines de préparation intensive suffisent pour progresser de 1 à 2 niveaux NCLC.",
  },
  {
    q: "Le simulateur IA corrige-t-il vraiment bien ?",
    a: "Notre simulateur est basé sur les critères officiels d’évaluation du TCF Canada. Il analyse la structure, le vocabulaire, la grammaire et la pertinence de vos productions en quelques secondes.",
  },
  {
    q: "Puis-je accéder à la plateforme depuis mon téléphone ?",
    a: "Absolument. Lumina est entièrement responsive et optimisée pour mobile, tablette et ordinateur. Révisez où que vous soyez, quand vous le souhaitez.",
  },
  {
    q: "Y a-t-il un accès gratuit ?",
    a: "Oui, vous pouvez découvrir l’interface et utiliser le calculateur NCLC sans créer de compte. L’accès complet aux tests et aux corrections IA nécessite un abonnement.",
  },
  {
    q: "Comment fonctionne le paiement ?",
    a: "Le paiement est sécurisé via Mobile Money (Orange Money, MTN MoMo) et carte bancaire. L’accès est activé immédiatement après confirmation du paiement.",
  },
];
</script>

// frontend/components/home/Faq.tsx
"use client";

import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQ = () => {
  const faqs = [
    {
      question: "Comment fonctionne la correction IA?",
      answer:
        "Notre IA analyse votre texte en 10 secondes et vous donne un score détaillé sur la grammaire, le vocabulaire, la syntaxe et la cohérence. Elle est entraînée sur 10,000+ copies TCF réelles pour garantir la fiabilité des corrections.",
    },
    {
      question: "Quelle est la différence entre correction IA et humaine?",
      answer:
        "La correction IA est instantanée et illimitée - parfaite pour identifier vos erreurs de grammaire et vocabulaire. La correction humaine valide votre méthodologie, structure d'argumentation et vous donne des conseils personnalisés pour maximiser votre score. Nous recommandons: IA pour la pratique quotidienne, humain pour la validation finale.",
    },
    {
      question: "Les séries sont-elles conformes au TCF Canada 2025?",
      answer:
        "Oui, toutes nos séries respectent strictement le format officiel TCF Canada 2025: mêmes types de questions, même durée, mêmes consignes. Nous mettons à jour régulièrement notre contenu selon les évolutions de l'examen.",
    },
    {
      question: "Combien de temps pour atteindre C1/C2?",
      answer:
        "Cela dépend de votre niveau de départ. En moyenne, nos utilisateurs progressent d'un niveau CECRL en 4-6 semaines avec une pratique régulière (3-4 séries par semaine). Si vous êtes déjà B2, vous pouvez viser C1 en 1-2 mois.",
    },
    {
      question: "Puis-je utiliser la plateforme sur mobile?",
      answer:
        "Oui, notre plateforme est 100% responsive. Vous pouvez pratiquer sur smartphone, tablette ou ordinateur. L'enregistrement audio pour l'expression orale fonctionne parfaitement sur mobile.",
    },
    {
      question: "Comment se passe l'activation après paiement?",
      answer:
        "L'activation est immédiate et automatique. Après paiement (Mobile Money, carte bancaire ou virement), vous recevez un email de confirmation et vous pouvez accéder instantanément à toutes les séries incluses dans votre plan.",
    },
    {
      question: "Y a-t-il une garantie satisfait ou remboursé?",
      answer:
        "Oui, nous offrons une garantie 7 jours satisfait ou remboursé. Si vous n'êtes pas satisfait de la plateforme pour quelque raison que ce soit, contactez-nous dans les 7 premiers jours pour un remboursement intégral.",
    },
    {
      question: "Puis-je annuler mon abonnement à tout moment?",
      answer:
        "Oui, vous pouvez annuler votre abonnement en 1 clic depuis votre espace personnel. Aucune pénalité, aucune question posée. Vous gardez accès jusqu'à la fin de votre période payée.",
    },
  ];

  return (
    <section className="lg:py-16  from-emerald-50 to-white dark:bg-slate-900">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 text-sm font-semibold mb-4">
            FAQ
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-4">
            Questions fréquentes
          </h2>
          <p className="text-lg text-slate-600 dark:text-slate-400">
            Tout ce que vous devez savoir sur Lumina TCF
          </p>
        </div>

        {/* Accordion */}
        <Accordion type="single" collapsible className="space-y-4">
          {faqs.map((faq, index) => (
            <AccordionItem
              key={index}
              value={`item-${index}`}
              className="border border-slate-200 dark:border-slate-800 rounded-lg px-6 bg-white dark:bg-slate-800/50"
            >
              <AccordionTrigger className="text-left hover:no-underline py-6">
                <span className="text-base font-semibold text-slate-900 dark:text-white pr-4">
                  {faq.question}
                </span>
              </AccordionTrigger>
              <AccordionContent className="pb-6  text-slate-600 dark:text-slate-400 leading-relaxed">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>

        {/* CTA Footer */}
        <div className="mt-12 mb-8 text-center p-8 bg-linear-to-r from-emerald-50 to-blue-50 dark:from-emerald-900/20 dark:to-blue-900/20 rounded-2xl border border-emerald-200 dark:border-emerald-800">
          <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">
            Vous avez d'autres questions?
          </h3>
          <p className="text-slate-600 dark:text-slate-400 mb-6">
            Notre équipe est là pour vous aider
          </p>

          <a
            href="mailto:support@luminatcf.com"
            className="inline-flex items-center justify-center px-6 py-3 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold rounded-lg transition-colors"
          >
            Contactez-nous
            <svg
              className="ml-2 w-4 h-4"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M14 5l7 7m0 0l-7 7m7-7H3"
              />
            </svg>
          </a>
        </div>
      </div>
    </section>
  );
};

export default FAQ;
